# Déclencheur du workflow
on:
  push:
    branches:
      - main # Dès qu'on push sur le main

jobs:
  push_to_registries:
    # Nom du workflow, ici j'ai mis le nom en fonction de ce qu'on a au labo à la question3
    name: Construire le conteneur et le publier sur le registre GitHub Packages
    # Environnement d'exécution : machine virtuelle Linux
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      actions: read
      id-token: write
    steps:
      # Étape 1 : Récupère le code source du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configure Docker Buildx pour des fonctionnalités avancées de build
      - name: Configurer Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Étape 3 : Connexion à GitHub Container Registry (GHCR)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Étape 4 : Construire le conteneur et le publier sur le registre GitHub Packages
      - name: Construire le conteneur et le publier sur le registre GitHub Packages
        uses: docker/build-push-action@v5
        with:
          context: . # Utilise le répertoire courant pour construire l'image
          push: true
          tags: ghcr.io/sim0nr/ue19-lab-05 # identifiant de l'image Docker taguée